Repository MettingApp/backend, pull requests merged in 2024-11, with the labels that each got.

#2 [Feat] basic configuration 구성
  build.gradle
  src/main/java/server/meeting/domain/meeting/model/Meeting.java
  src/main/java/server/meeting/domain/member/model/Member.java
  src/main/java/server/meeting/domain/record/model/Record.java
  src/main/java/server/meeting/global/api/Api.java
  src/main/java/server/meeting/global/api/Result.java
  src/main/java/server/meeting/global/error/ErrorCodeInterface.java
  src/main/java/server/meeting/global/error/ErrorType.java
  src/main/java/server/meeting/global/exception/ApiException.java
  src/main/java/server/meeting/global/exception/ApiExceptionInterface.java
Labels: feat, fix

#5 [feat] S3 업로드 구현하기
  build.gradle
  src/main/java/server/meeting/domain/meeting/model/Meeting.java
  src/main/java/server/meeting/domain/meeting/model/MeetingMembers.java
  src/main/java/server/meeting/domain/member/model/Member.java
  src/main/java/server/meeting/global/config/jpaConfig/JpaConfig.java
  src/main/java/server/meeting/global/error/ErrorType.java
  src/main/java/server/meeting/global/s3/S3Config.java
  src/main/java/server/meeting/global/s3/S3Service.java
  src/test/java/server/meeting/global/s3/S3ServiceTest.java
Labels: feat, fix

#7 [Feat] 회원가입, JWT를 이용한 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/server/meeting/domain/member/controller/MemberController.java
  src/main/java/server/meeting/domain/member/dto/MemberSignInRequestDto.java
  src/main/java/server/meeting/domain/member/dto/MemberSignUpRequestDto.java
  src/main/java/server/meeting/domain/member/dto/MemberSignUpResponseDto.java
  src/main/java/server/meeting/domain/member/model/Member.java
  src/main/java/server/meeting/domain/member/model/Role.java
  src/main/java/server/meeting/domain/member/repository/MemberRepository.java
  src/main/java/server/meeting/domain/member/service/CustomUserDetailsServiceImpl.java
  src/main/java/server/meeting/domain/member/service/MemberService.java
  src/main/java/server/meeting/domain/member/service/MemberServiceImp.java
  src/main/java/server/meeting/global/common/TokenDto.java
  src/main/java/server/meeting/global/config/SecurityConfig.java
  src/main/java/server/meeting/global/error/ErrorType.java
  src/main/java/server/meeting/global/filter/JwtAuthFilter.java
  src/main/java/server/meeting/global/util/JwtProvider.java
Labels: feat, fix

#9 [Feat] 회의 crud 구현하기
  src/main/java/server/meeting/domain/meeting/controller/MeetingController.java
  src/main/java/server/meeting/domain/meeting/dto/MeetingCreateReq.java
  src/main/java/server/meeting/domain/meeting/dto/MeetingDetailResDto.java
  src/main/java/server/meeting/domain/meeting/dto/MeetingResDto.java
  src/main/java/server/meeting/domain/meeting/model/Meeting.java
  src/main/java/server/meeting/domain/meeting/model/MeetingMembers.java
  src/main/java/server/meeting/domain/meeting/repository/CustomMeetingRepository.java
  src/main/java/server/meeting/domain/meeting/repository/MeetingMembersRepository.java
  src/main/java/server/meeting/domain/meeting/repository/MeetingRepository.java
  src/main/java/server/meeting/domain/meeting/repositoryImpl/MeetingRepositoryImpl.java
  src/main/java/server/meeting/domain/meeting/service/MeetingService.java
  src/main/java/server/meeting/domain/member/controller/MemberController.java
  src/main/java/server/meeting/domain/member/service/MemberServiceImp.java
  src/main/java/server/meeting/domain/record/dto/RecorderResDto.java
  src/main/java/server/meeting/domain/record/model/Recorder.java
  src/main/java/server/meeting/domain/record/repository/RecorderRepository.java
  src/main/java/server/meeting/domain/team/controller/TeamController.java
  src/main/java/server/meeting/domain/team/service/TeamServiceImpl.java
  src/main/java/server/meeting/global/api/Api.java
  src/main/java/server/meeting/global/api/Result.java
  src/main/java/server/meeting/global/config/jpaConfig/JpaConfig.java
  src/main/java/server/meeting/global/error/ErrorCodeInterface.java
  src/main/java/server/meeting/global/exception/ApiException.java
  src/main/java/server/meeting/global/exception/ApiExceptionHandler.java
  src/main/java/server/meeting/global/exception/ApiExceptionInterface.java
  src/main/java/server/meeting/global/exception/ApiExceptionResponse.java
  src/main/java/server/meeting/global/exception/ErrorType.java
  src/main/java/server/meeting/global/filter/JwtAuthFilter.java
  src/main/java/server/meeting/global/s3/S3Service.java
  src/main/java/server/meeting/global/success/SuccessResponse.java
  src/main/java/server/meeting/global/success/SuccessResponseStatus.java
  src/main/java/server/meeting/global/success/SuccessStatus.java
  src/main/resources/data.sql
  src/test/java/server/meeting/global/s3/S3ServiceTest.java
Labels: feat, fix, hot fix

#10 feat: swagger 구현
  build.gradle
  src/main/java/server/meeting/global/config/SecurityConfig.java
  src/main/java/server/meeting/global/config/SwaggerConfig.java
Labels: feat

#12 [Feat/Fix] Member, Team 연관관계 변경 및 팀 가입, 팀 생성 로직 변경
  src/main/java/server/meeting/domain/member/model/Member.java
  src/main/java/server/meeting/domain/member/repository/MemberRepository.java
  src/main/java/server/meeting/domain/team/model/Team.java
  src/main/java/server/meeting/domain/team/model/TeamMember.java
  src/main/java/server/meeting/domain/team/repository/TeamMemberRepository.java
  src/main/java/server/meeting/domain/team/service/TeamServiceImpl.java
  src/main/java/server/meeting/global/exception/ErrorType.java
Labels: feat, fix

#13 [Fix] TeamId에 따른 MemberNickName 리스트 조회 수정
  src/main/java/server/meeting/domain/team/repository/CustomTeamMemberRepository.java
  src/main/java/server/meeting/domain/team/repositoryImpl/TeamMemberRepositoryImpl.java
  src/main/java/server/meeting/domain/team/service/TeamServiceImpl.java
Labels: hot fix
